# Generated by Django 4.2 on 2023-04-04 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('COD_actividad', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Costo', models.FloatField(max_length=(9, 2))),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('Tipo_ID', models.CharField(max_length=10)),
                ('NID', models.IntegerField(primary_key=True, serialize=False)),
                ('Razon_social', models.CharField(max_length=70)),
                ('Direccion', models.CharField(max_length=70)),
                ('Email', models.CharField(max_length=70)),
                ('Telefono', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ingeniero',
            fields=[
                ('COD_ingeniero', models.IntegerField(primary_key=True, serialize=False)),
                ('Identificacion', models.IntegerField()),
                ('Nombres', models.CharField(max_length=70)),
                ('Apellidos', models.CharField(max_length=70)),
                ('ROL', models.CharField(max_length=50)),
                ('Direccion', models.CharField(max_length=80)),
                ('Telefono', models.IntegerField()),
                ('Email', models.CharField(max_length=70)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('Codigo', models.IntegerField(primary_key=True, serialize=False)),
                ('Nombre', models.CharField(max_length=50)),
                ('Descripcion', models.TextField(max_length=500)),
                ('Costo', models.FloatField(max_length=(9, 2))),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente')),
                ('ingeniero', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ingeniero')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Bitacora',
            fields=[
                ('Fecha', models.DateField()),
                ('COD_bitacora', models.AutoField(primary_key=True, serialize=False)),
                ('Horas_laboradas', models.FloatField(max_length=5)),
                ('Cantidad_de_fuentes_trabajados', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 'Otro valor')], default=1)),
                ('Numero_de_fuentes', models.IntegerField(blank=True, max_length=2, null=True)),
                ('Tipos_de_fuentes_trabajados', models.IntegerField(choices=[(1, 'Seleccione'), (2, 'RPG'), (3, 'RPGLE'), (3, 'RPGLE y RPG'), (3, 'Otro')], default=1)),
                ('Indique_los_fuentes_trabajados', models.CharField(blank=True, max_length=50, null=True)),
                ('Estado_de_los_fuentes_trabajados', models.IntegerField(choices=[(1, 'Seleccione'), (2, 'En proceso'), (3, 'Terminado')], default=1)),
                ('Nota', models.TextField(blank=True, max_length=300, null=True)),
                ('Actividad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.actividad')),
                ('Proyecto', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proyecto')),
            ],
        ),
        migrations.AddField(
            model_name='actividad',
            name='ingeniero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ingeniero'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='proyecto',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.proyecto'),
        ),
        migrations.AddField(
            model_name='actividad',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
