# Generated by Django 4.2 on 2023-04-13 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_alter_bitacora_numero_de_fuentes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ingeniero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ingeniero'),
        ),
    ]
