# Generated by Django 4.2 on 2023-04-14 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_rename_ingeniero_cliente_ingeniero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='Ingeniero',
            new_name='Ingenieros_a_cargo',
        ),
        migrations.AddField(
            model_name='bitacora',
            name='cliente',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.cliente'),
        ),
    ]
