# Generated by Django 4.2 on 2023-04-20 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_rename_ingeniero_cliente_ingenieros_a_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Tipo_ID',
        ),
        migrations.AddField(
            model_name='cliente',
            name='Tipo_de_identificacion',
            field=models.IntegerField(choices=[(1, 'Seleccione'), (2, 'Cedula de ciudadania'), (3, 'Cedula de extranjeria'), (4, 'NIT')], default=1),
        ),
    ]
