# Generated by Django 4.2 on 2023-05-02 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_remove_cliente_tipo_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cliente',
            name='Ingenieros_a_cargo',
        ),
        migrations.RemoveField(
            model_name='cliente',
            name='Tipo_de_identificacion',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='user',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='ingeniero',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ingeniero',
            field=models.ManyToManyField(to='tasks.ingeniero'),
        ),
    ]
