# Generated by Django 4.2 on 2023-05-02 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_remove_cliente_ingenieros_a_cargo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='ingeniero',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ingeniero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasks.ingeniero'),
        ),
    ]
