# Generated by Django 4.2 on 2023-05-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_remove_proyecto_ingeniero_proyecto_ingeniero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingeniero',
            name='user',
        ),
    ]
