# Generated by Django 4.2 on 2023-05-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_cliente_tipo_de_identificacion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='ingeniero',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ingeniero',
            field=models.ManyToManyField(null=True, to='tasks.ingeniero'),
        ),
    ]
