# Generated by Django 4.2 on 2023-05-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0011_remove_proyecto_ingeniero_proyecto_ingeniero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='ingeniero',
            field=models.ManyToManyField(to='tasks.ingeniero'),
        ),
    ]
