# Generated by Django 4.2 on 2023-05-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0013_remove_proyecto_ingeniero_proyecto_ingeniero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='ingeniero',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='ingeniero',
            field=models.ManyToManyField(to='tasks.ingeniero'),
        ),
    ]
