# Generated by Django 4.2 on 2023-05-02 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_remove_proyecto_ingeniero_proyecto_ingeniero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proyecto',
            old_name='ingeniero',
            new_name='ingenieros_a_cargo',
        ),
    ]
