# Generated by Django 4.2 on 2023-05-02 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0015_rename_ingeniero_proyecto_ingenieros_a_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='Indique_los_fuentes_trabajados',
        ),
    ]
