# Generated by Django 4.2 on 2023-05-11 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0016_remove_bitacora_indique_los_fuentes_trabajados'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitacora',
            name='Numero_de_fuentes',
        ),
        migrations.AlterField(
            model_name='actividad',
            name='COD_actividad',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='Cantidad_de_fuentes_trabajados',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bitacora',
            name='Tipos_de_fuentes_trabajados',
            field=models.IntegerField(choices=[(1, 'Seleccione'), (2, 'AZ7'), (3, 'RPG'), (4, 'RPGLE'), (5, 'RPGLE y RPG'), (6, 'AZ7 y RPG'), (7, 'AZ7 y RPGLE')], default=1),
        ),
        migrations.AlterField(
            model_name='ingeniero',
            name='COD_ingeniero',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='Codigo',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
