# Generated by Django 4.1.7 on 2023-05-24 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0017_remove_bitacora_numero_de_fuentes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bitacora',
            name='Tipos_de_fuentes_trabajados',
            field=models.IntegerField(choices=[(1, 'Seleccione'), (2, 'RPG'), (3, 'RPGLE'), (4, 'RPGLE y RPG')], default=1),
        ),
    ]
