# Generated by Django 4.1.7 on 2023-05-24 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0018_alter_bitacora_tipos_de_fuentes_trabajados'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitacora',
            name='Nombre',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
